#!/usr/bin/env bash
# Bash script on how to install nginx server and write content to the root

# update the package list first
sudo apt-get -y update && sudo apt-get -y upgrade
sudo install nginx -y

mkdir /etc/nginx/html

touch /etc/nginx/html/index.html

echo "Holberton School" > /etc/nginx/html/index.html

service nginx restart 
