#!/usr/bin/env bash
# Bash script on how to install nginx server and write content to the root

# update the package list first
sudo apt-get -y update && sudo apt-get -y upgrade
sudo install nginx -y

sudo mkdir /etc/nginx/html

sudo touch /etc/nginx/html/index.html

sudo echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart 
